In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('03 - Case MOBILITY SHIFT\Bus_Stops.csv')
df.head()

,Stop_ID,Stop_Name,Latitude,Longitude,Stop_Type,Zone
0,1,Res_InternationalCity_Stop_01,25.179934,55.412235,Metro_Link,Res_InternationalCity
1,2,Core_Deira_Stop_02,25.242762,55.315378,Regular,Core_Deira
2,3,Core_Deira_Stop_03,25.296584,55.324349,Regular,Core_Deira
3,4,Res_InternationalCity_Stop_04,25.158382,55.404497,Regular,Res_InternationalCity
4,5,CBD_BusinessBay_Stop_05,25.190839,55.235734,Regular,CBD_BusinessBay

In [4]:
df1 = pd.read_csv('03 - Case MOBILITY SHIFT\Bus_Stops.csv')
df1.head()

,Stop_ID,Stop_Name,Latitude,Longitude,Stop_Type,Zone
0,1,Res_InternationalCity_Stop_01,25.179934,55.412235,Metro_Link,Res_InternationalCity
1,2,Core_Deira_Stop_02,25.242762,55.315378,Regular,Core_Deira
2,3,Core_Deira_Stop_03,25.296584,55.324349,Regular,Core_Deira
3,4,Res_InternationalCity_Stop_04,25.158382,55.404497,Regular,Res_InternationalCity
4,5,CBD_BusinessBay_Stop_05,25.190839,55.235734,Regular,CBD_BusinessBay

In [ ]:
df2 = pdf.read_csv